version: "3.5"

services:
  jest:
    container_name: ebusiness-jest
    build:
      context: .
      dockerfile: ./containers/node/Dockerfile
    volumes:
      - .:/var/www/html
    restart: 'no'
    command: 'npm run test'
    environment:
      - NODE_ENV=TEST
      - DB_DIALECT_=sqlite
      - DB_STORAGE=./db_test.sqlite
      - APP_KEY=123456
  lint:
    container_name: ebusiness-eslint
    build:
      context: .
      dockerfile: containers/node/Dockerfile
    volumes:
      - .:/var/www/html
    restart: 'no'
    command: 'npm run lint'

networks:
  default:
    external:
      name: ebusiness-network
